//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISoapPrinterService")]
    public interface ISoapPrinterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addCHFByUID", ReplyAction="http://tempuri.org/ISoapPrinterService/addCHFByUIDResponse")]
        bool addCHFByUID(int idUser, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addCHFByUID", ReplyAction="http://tempuri.org/ISoapPrinterService/addCHFByUIDResponse")]
        System.Threading.Tasks.Task<bool> addCHFByUIDAsync(int idUser, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/getUsernameByCardID", ReplyAction="http://tempuri.org/ISoapPrinterService/getUsernameByCardIDResponse")]
        string getUsernameByCardID(int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/getUsernameByCardID", ReplyAction="http://tempuri.org/ISoapPrinterService/getUsernameByCardIDResponse")]
        System.Threading.Tasks.Task<string> getUsernameByCardIDAsync(int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addQuotaByUsername", ReplyAction="http://tempuri.org/ISoapPrinterService/addQuotaByUsernameResponse")]
        double addQuotaByUsername(string Username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addQuotaByUsername", ReplyAction="http://tempuri.org/ISoapPrinterService/addQuotaByUsernameResponse")]
        System.Threading.Tasks.Task<double> addQuotaByUsernameAsync(string Username, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/convertCHFToQuota", ReplyAction="http://tempuri.org/ISoapPrinterService/convertCHFToQuotaResponse")]
        decimal convertCHFToQuota(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/convertCHFToQuota", ReplyAction="http://tempuri.org/ISoapPrinterService/convertCHFToQuotaResponse")]
        System.Threading.Tasks.Task<decimal> convertCHFToQuotaAsync(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/convertQuotaToCHF", ReplyAction="http://tempuri.org/ISoapPrinterService/convertQuotaToCHFResponse")]
        decimal convertQuotaToCHF(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/convertQuotaToCHF", ReplyAction="http://tempuri.org/ISoapPrinterService/convertQuotaToCHFResponse")]
        System.Threading.Tasks.Task<decimal> convertQuotaToCHFAsync(decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addCHFByUsername", ReplyAction="http://tempuri.org/ISoapPrinterService/addCHFByUsernameResponse")]
        bool addCHFByUsername(string name, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/addCHFByUsername", ReplyAction="http://tempuri.org/ISoapPrinterService/addCHFByUsernameResponse")]
        System.Threading.Tasks.Task<bool> addCHFByUsernameAsync(string name, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/getUserAccount", ReplyAction="http://tempuri.org/ISoapPrinterService/getUserAccountResponse")]
        string getUserAccount(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapPrinterService/getUserAccount", ReplyAction="http://tempuri.org/ISoapPrinterService/getUserAccountResponse")]
        System.Threading.Tasks.Task<string> getUserAccountAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapPrinterServiceChannel : App.ServiceReference1.ISoapPrinterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapPrinterServiceClient : System.ServiceModel.ClientBase<App.ServiceReference1.ISoapPrinterService>, App.ServiceReference1.ISoapPrinterService {
        
        public SoapPrinterServiceClient() {
        }
        
        public SoapPrinterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapPrinterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapPrinterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapPrinterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addCHFByUID(int idUser, decimal amount) {
            return base.Channel.addCHFByUID(idUser, amount);
        }
        
        public System.Threading.Tasks.Task<bool> addCHFByUIDAsync(int idUser, decimal amount) {
            return base.Channel.addCHFByUIDAsync(idUser, amount);
        }
        
        public string getUsernameByCardID(int cardId) {
            return base.Channel.getUsernameByCardID(cardId);
        }
        
        public System.Threading.Tasks.Task<string> getUsernameByCardIDAsync(int cardId) {
            return base.Channel.getUsernameByCardIDAsync(cardId);
        }
        
        public double addQuotaByUsername(string Username, decimal amount) {
            return base.Channel.addQuotaByUsername(Username, amount);
        }
        
        public System.Threading.Tasks.Task<double> addQuotaByUsernameAsync(string Username, decimal amount) {
            return base.Channel.addQuotaByUsernameAsync(Username, amount);
        }
        
        public decimal convertCHFToQuota(decimal amount) {
            return base.Channel.convertCHFToQuota(amount);
        }
        
        public System.Threading.Tasks.Task<decimal> convertCHFToQuotaAsync(decimal amount) {
            return base.Channel.convertCHFToQuotaAsync(amount);
        }
        
        public decimal convertQuotaToCHF(decimal amount) {
            return base.Channel.convertQuotaToCHF(amount);
        }
        
        public System.Threading.Tasks.Task<decimal> convertQuotaToCHFAsync(decimal amount) {
            return base.Channel.convertQuotaToCHFAsync(amount);
        }
        
        public bool addCHFByUsername(string name, decimal amount) {
            return base.Channel.addCHFByUsername(name, amount);
        }
        
        public System.Threading.Tasks.Task<bool> addCHFByUsernameAsync(string name, decimal amount) {
            return base.Channel.addCHFByUsernameAsync(name, amount);
        }
        
        public string getUserAccount(string name) {
            return base.Channel.getUserAccount(name);
        }
        
        public System.Threading.Tasks.Task<string> getUserAccountAsync(string name) {
            return base.Channel.getUserAccountAsync(name);
        }
    }
}
